# Generated by Django 6.0.1 on 2026-01-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timeframe',
            field=models.DateTimeField(null=True),
        ),
    ]
