# Generated by Django 6.0.1 on 2026-01-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_timeframe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='timeframe',
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, help_text='Срок выполнения задачи (необязательно)', null=True, verbose_name='Срок выполнения'),
        ),
        migrations.AddField(
            model_name='task',
            name='due_time',
            field=models.TimeField(blank=True, help_text='Время выполнения (необязательно)', null=True, verbose_name='Время выполнения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
