# Generated by Django 6.0.1 on 2026-01-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'Высокий'), ('MEDIUM', 'Низкий'), ('LOW', 'Средний')], max_length=100, null=True),
        ),
    ]
